version: "3"

services:
  client:
    build: ./client
    command: npm start
    ports:
      - "3000:3000"
    expose:
      - 3000
    volumes:
      - "./client/:/client"
    networks:
      - portafolio_net

  server:
    build: ./server
    command: npm start
    ports:
      - "8000:8000"
    expose:
      - 8000
    env_file:
      - ./server/.env
    volumes:
      - "./server:/server"
    networks:
      - portafolio_net

networks:
  portafolio_net:
    driver: bridge
