version: "3"

services:
  client:
    build: ./client
    command: npm start
    ports:
      - "3000:3000"
    expose:
      - 3000
    volumes:
      - "./client/:/client"
    networks:
      - portafolio_net

networks:
  portafolio_net:
    driver: bridge
