version: "3.9"

services:
  client:
    build:
      context: ./client
      dockerfile: dockerfile.dev
    command: npm start
    ports:
      - "3000:3000"
    volumes:
      - "./client/:/client"
    networks:
      - portafolio_net

  server:
    build:
      context: ./server
      dockerfile: dockerfile.dev
    command: npm run dev
    ports:
      - "8000:8000"
    env_file:
      - ./server/.dev.env
    volumes:
      - "./server:/server"
    networks:
      - portafolio_net

networks:
  portafolio_net:
    driver: bridge
